In [26]:
import pandas as pd
pd.__version__

'2.2.2'

In [27]:
s = pd.Series({"Name": "Khawfang", "Age": 17, "Height": 161})
s

Name      Khawfang
Age             17
Height         161
dtype: object

In [28]:
d = {"Name": ["พี่เว", "ฟ้าใส", "ข้าวฟ่าง"], "Age": [22, 16, 17], "isGradted": [True, False, False]}
df = pd.DataFrame(data=d)
df

       Name  Age  isGradted
0     พี่เว   22       True
1     ฟ้าใส   16      False
2  ข้าวฟ่าง   17      False

In [29]:
df.dtypes

Name         object
Age           int64
isGradted      bool
dtype: object

In [54]:
pd.set_option('display.max_rows', 20)

In [65]:
df2 = pd.read_csv("tips.csv")
df2

     total_bill   tip     sex smoker   day    time  size
0         16.99   NaN  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
df2.describe()

In [69]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         243 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [71]:
df2.head() # 5 ตัวแรก

   total_bill   tip     sex smoker  day    time  size
0       16.99   NaN  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df2.head(20)

In [ ]:
df2.tail() # 5ตัวท้าย

In [ ]:
df2.tail(20)

In [66]:
df2.shape

(244, 7)

In [72]:
# df2.isna()
df2.isna().any() # chack is NAN (False = not NAN)
# df2.isna().all()
# df2.isna().all().all()

total_bill    False
tip            True
sex           False
smoker        False
day           False
time          False
size          False
dtype: bool

## Selecting Data

In [82]:
df.head()

       Name  Age  isGradted
0     พี่เว   22       True
1     ฟ้าใส   16      False
2  ข้าวฟ่าง   17      False

In [85]:
df['Name']
df['Age']
df[['Name', 'Age']]

       Name  Age
0     พี่เว   22
1     ฟ้าใส   16
2  ข้าวฟ่าง   17

In [88]:
df.loc[0]
df.loc[2]

Name         ข้าวฟ่าง
Age                17
isGradted       False
Name: 2, dtype: object

## Manipulate Data

- change element

In [89]:
df.head()

       Name  Age  isGradted
0     พี่เว   22       True
1     ฟ้าใส   16      False
2  ข้าวฟ่าง   17      False

In [90]:
df.loc[2, 'Age'] = 18
df

       Name  Age  isGradted
0     พี่เว   22       True
1     ฟ้าใส   16      False
2  ข้าวฟ่าง   18      False

- rename columns

In [96]:
df.rename(columns={'isGraduated': 'isGrad', 'Name': 'Fullname'})

   Fullname  Age  isGradted
0     พี่เว   22       True
1     ฟ้าใส   16      False
2  ข้าวฟ่าง   18      False